### ISSUE TITLE
Tests don't run

### ISSUE THREAD

**Issue by ig3** [ig3/epub.js#3]
`npm test` fails with:

```
> @ig3/epubjs@0.3.93 test
> karma start --single-run --browsers ChromeHeadlessNoSandbox

09 04 2023 06:55:00.153:ERROR [plugin]: Error during loading "/home/ian/dev/epub.js/node_modules/karma-phantomjs-launcher" plugin:
  The "path" argument must be of type string. Received null
...
```

**Comment by ig3** [comment]
I tried cloning https://github.com/futurepress/epub.js.git and `npm install` doesn't run successfully, let alone tests.

**Comment by ig3** [comment]
I got the tests running by completing the install of phantomjs-prebuilt:

```
$ cd node_modules/phantomjs-prebuilt
$ export OPENSSL_CONF=/etc/ssl
$ n exec 16.40.0 node ./install.js
```
This produces lib/location.js which, for some reason (maybe because OPENSSL_CONF wasn't set) was not created at install, though I didn't notice an error.

Then run the tests:

```
$ export CHROME_BIN=/usr/bin/chromium
$ n exec 16.14.0 npm test
```

I don't have Chrome installed but I do have Chromium and that seems to be good enough to run the tests.

The tests run with:

```
SUMMARY:
✔ 57 tests completed
ℹ 1 test skipped
✖ 4 tests failed

FAILED TESTS:
  section
    ✖ finds a single result in a section
      Chrome Headless 111.0.5563.64 (Linux x86_64)
    AssertionError: 'epubcfi(/6/8!/4/2/16,/1:275,/1:323)' == 'epubcfi(/6/8[chapter_001]!/4/2/16,/1:275,/1:323)'
        at test/section.js:37882:57
        at Array.forEach (<anonymous>)
        at test/section.js:37880:38

    ✖ finds multiple results in a section
      Chrome Headless 111.0.5563.64 (Linux x86_64)
    AssertionError: 'epubcfi(/6/8!/4/2/8,/1:240,/1:252)' == 'epubcfi(/6/8[chapter_001]!/4/2/8,/1:240,/1:252)'
        at test/section.js:37901:57
        at Array.forEach (<anonymous>)
        at test/section.js:37899:38

    ✖ finds result that spanning multiple document nodes, tag at ending
      Chrome Headless 111.0.5563.64 (Linux x86_64)
    AssertionError: 'epubcfi(/6/26!/4/2/6,/1:5,/2/1:3)' == 'epubcfi(/6/26[chapter_010]!/4/2/6,/1:5,/2/1:3)'
        at test/section.js:37922:55

    ✖ finds result that spanning multiple document nodes, tag at middle
      Chrome Headless 111.0.5563.64 (Linux x86_64)
    AssertionError: 'epubcfi(/6/26!/4/2/6,/1:5,/3:12)' == 'epubcfi(/6/26[chapter_010]!/4/2/6,/1:5,/3:12)'
        at test/section.js:37940:55
```

That's not too bad.

**Comment by ig3** [comment]
Updated README with notes about how to get tests running.
