### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by ig3** [ig3/epub.js#4]
With node v18.13.0, `npm install` fails with:

```
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/ian/test/test-epubjs/epub.js/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/ian/test/test-epubjs/epub.js/node_modules/webpack/lib/NormalModule.js:417:16)

```

So, the fault appears to manifest in webpack.

**Comment by ig3** [comment]
According to [this stackoverflow question](https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported), the issue was introduced by node v17 fixing an SSL security vulnerability with a breaking change.

**Comment by ig3** [comment]
Running the installer with  node v16.14.0 succeeds.

**Comment by ig3** [comment]
See:
 * https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported
 * https://webpack.js.org/configuration/output/
 * https://nodejs.org/api/crypto.html#crypto_crypto_createhash_algorithm_options
 * https://github.com/webpack/webpack/issues/14532

In particular, from the last:

> We are planning to migrate to a different hash function anyway for webpack 6. So currently you will have to use output.hashFunction: "xxhash64" in configuration to fix that. Or --openssl-legacy-provider

Since I don't want to use the legacy provider and that option may since have been removed, the best option without upgrading webpack seems to be to use xxhash64.

**Comment by ig3** [comment]
I tried setting hashFunction is webpack.config.js:

```
  output: {
    path: path.resolve("./dist"),
    filename: filename,
    sourceMapFilename: sourceMapFilename,
    library: "ePub",
    libraryTarget: "umd",
    libraryExport: "default",
    publicPath: "/dist/",
    hashFunction: 'xxhash64'
  },
```

But this also failed with:

```
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: Digest method not supported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/ian/test/test-epubjs/epub.js/node_modules/webpack/lib/util/createHash.js:136:53)
    at NormalModule._initBuildHash (/home/ian/test/test-epubjs/epub.js/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/ian/test/test-epubjs/epub.js/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/ian/test/test-epubjs/epub.js/node_modules/webpack/lib/NormalModule.js:503:5
...
```

https://stackoverflow.com/a/74125491/1339621 suggests that the xxhash64 algorithm is only supported if a node add-on is installed. But I want a solution that works without a node add-on.

**Comment by ig3** [comment]
I tried hashFunction sha256 but this too failed, with:

```
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/ian/test/test-epubjs/epub.js/node_modules/webpack/lib/util/createHash.js:136:53)
    at ConcatenatedModule._createIdentifier (/home/ian/test/test-epubjs/epub.js/node_modules/webpack/lib/optimize/ConcatenatedModule.js:563:16)
    at new ConcatenatedModule (/home/ian/test/test-epubjs/epub.js/node_modules/webpack/lib/optimize/ConcatenatedModule.js:445:27)
    at /home/ian/test/test-epubjs/epub.js/node_modules/webpack/lib/optimize/ModuleConcatenationPlugin.js:250:26
    at SyncBailHook.eval [as call] (eval at create (/home/ian/test/test-epubjs/epub.js/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:12:16)
    at SyncBailHook.lazyCompileHook (/home/ian/test/test-epubjs/epub.js/node_modules/tapable/lib/Hook.js:154:20)
    at /home/ian/test/test-epubjs/epub.js/node_modules/webpack/lib/Compilation.js:1351:37
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/ian/test/test-epubjs/epub.js/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (/home/ian/test/test-epubjs/epub.js/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.seal (/home/ian/test/test-epubjs/epub.js/node_modules/webpack/lib/Compilation.js:1342:27)
    at /home/ian/test/test-epubjs/epub.js/node_modules/webpack/lib/Compiler.js:675:18
    at /home/ian/test/test-epubjs/epub.js/node_modules/webpack/lib/Compilation.js:1261:4
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/ian/test/test-epubjs/epub.js/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:31:1)
    at AsyncSeriesHook.lazyCompileHook (/home/ian/test/test-epubjs/epub.js/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/home/ian/test/test-epubjs/epub.js/node_modules/webpack/lib/Compilation.js:1253:28)
    at /home/ian/test/test-epubjs/epub.js/node_modules/webpack/lib/Compiler.js:672:17
    at eval (eval at create (/home/ian/test/test-epubjs/epub.js/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at /home/ian/test/test-epubjs/epub.js/node_modules/webpack/lib/Compilation.js:1185:12
    at /home/ian/test/test-epubjs/epub.js/node_modules/webpack/lib/Compilation.js:1097:9
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

But on investigation, I found it was still trying to use the deprecated md4 algorithm.

webpack/lib/optimize/ConcatenatedModule.js has hard coded md4.

Given it is hard coded, there seems no option but to upgrade webpack. But there are dependencies of several webpack packages:

```
   "webpack": "^4.43.0",
    "webpack-cli": "^3.3.11",
    "webpack-dev-middleware": "^3.7.2",
    "webpack-dev-server": "^3.11.0"
```

Might it be necessary to upgrade all of them?

**Comment by ig3** [comment]
Updating webpack to 5.78.0 caused some warnings on npm install:

```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @ig3/epubjs@0.3.93
npm WARN Found: webpack@4.43.0
npm WARN node_modules/webpack
npm WARN   dev webpack@"^5.78.0" from the root project
npm WARN   3 more (babel-loader, karma-webpack, raw-loader)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer webpack@"^4.0.0" from karma-webpack@4.0.2
npm WARN node_modules/karma-webpack
npm WARN   dev karma-webpack@"^4.0.2" from the root project
```

But the install seems to have finished.

However, npm test fails with:

```
> @ig3/epubjs@0.3.93 test
> karma start --single-run --browsers ChromeHeadlessNoSandbox

09 04 2023 11:42:50.322:ERROR [plugin]: Error during loading "/home/ian/test/test-epubjs/epub.js/node_modules/karma-phantomjs-launcher" plugin:
  The "path" argument must be of type string. Received null
09 04 2023 11:42:50.341:ERROR [plugin]: Cannot find plugin "/home/ian/test/test-epubjs/epub.js/node_modules/karma-webpack".
  Did you forget to install it?
  npm install /home/ian/test/test-epubjs/epub.js/node_modules/karma-webpack --save-dev
09 04 2023 11:42:50.343:ERROR [preprocess]: Can not load "webpack", it is not registered!
  Perhaps you are missing some plugin?
```

Maybe because karma's peer dependency wasn't met?

**Comment by ig3** [comment]
Fixed by https://github.com/ig3/epub.js/commit/09efb695248e70c40845dbebc4db95ebf6d0eaa1
